# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Avocodable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'PromiseKit'

  target 'AvocodableTests' do
    inherit! :search_paths

  end

end
